name = "Portfolio"
license = "MIT"
licenselink = "https://github.com/matfin/annachristoffer/blob/master/annachristoffer/themes/portfolio/LICENSE.md"
description = "Theme for the portfolio website for Anna Claire Christoffer"
homepage = "http://annachristoffer.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Matt Finucane"
  homepage = "http://mattfinucane.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
