version: '3'

services:
  
  ac-site-build:
    container_name: ac_site_build
    restart: on-failure
    build:
      context: .docker/site
      dockerfile: Dockerfile
      args:
        hugo_version: "0.24"
    ports:
      - "1313:1313"
    volumes:
      - ./:/opt:ro
    command: hugo -s /opt/site -b http://annachristoffer.build --config=./site/build.yml -d ../public

  ac-nginx-build:
    container_name: ac_nginx_build
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.build.conf
    links: 
      - ac-site-build
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

  ac-js-build:
    container_name: ac_js_build
    restart: on-failure
    image: node:7.9.0
    environment:
      - SCRIPTS_DEST=./public/js
      - SVG_DEST=./public/svg
      - FAVICONS_DEST=./public/favicons
    volumes: 
      - ./:/opt:rw
    links:
      - ac-site-build
    depends_on:
      - ac-site-build
    command: sh -c "npm install -g gulp bower && && cd /opt && npm install && npm start"

  ac-sass-build:
    container_name: ac_sass_build
    image: ruby:2.1-alpine
    restart: on-failure
    volumes:
      - ./:/opt:rw
    links: 
      - ac-site-build
    depends_on:
      - ac-site-build
    command: sh -c "gem install sass && sass --watch /opt/assets/sass/main.sass:/opt/site/static/css/main.css"
  