version: '3'

services:

  ac-assets:
    image: node:7.7.4
    container_name: assetbuild
    volumes: 
      - ./:/opt:rw
    command: bash -c "cd /opt && npm install -g gulp && npm install -g bower && npm link gulp && npm install && gulp build"

  ac-site:
    container_name: gohugo
    build:
      context: .docker/site
      dockerfile: Dockerfile
    volumes:
      - ./:/opt:rw
    links:
      - ac-assets
    depends_on:
      - ac-assets