version: '3'

services:

  ac-assets:
    image: node:7.7.4
    container_name: assetbuild
    volumes: 
      - ./:/opt:rw
    links:
      - ac-site
    depends_on:
      - ac-site
    command: bash -c "cd /opt && npm install -g gulp && npm install -g bower && npm link gulp && npm install && bower install --allow-root && gulp build"

  ac-nginx:
    container_name: nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.build.conf
    volumes: 
      - ./media:/opt/media:ro
      - ./public:/opt/public:ro
    links: 
      - ac-site
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

  ac-site:
    container_name: site
    build:
      context: .docker/site
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - ./:/opt:rw
    command: hugo -s ./annachristoffer -b http://annachristoffer.build --config=./annachristoffer/config.build.toml -d ../public