version: '2'

services:
  site:
    container_name: 'ac_site'
    environment: 
      - VERSION=0.19
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/opt

volumes:
  data:
    driver: 'local'