version: '2'

services:
  ac-site:
    container_name: 'gohugo'
    environment: 
      - HUGO_TITLE=Anna Claire Christoffer
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/opt
    ports: 
      - "1313:1313"
    command: hugo server -s /opt/annachristoffer --config=/opt/annachristoffer/config.dev.toml --bind "0.0.0.0"

  ac-nginx:
    container_name: 'nginx'
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    links: 
      - ac-site
    ports:
      - "80:80"

volumes:
  data:
    driver: 'local'