version: '2'

services:
  site:
    container_name: 'ac_site'
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/opt
    ports: 
      - 1313:1313

volumes:
  data:
    driver: 'local'