version: '3'

services:

  ac-site-development:
    container_name: gohugo-dev
    environment: 
      - HUGO_TITLE=Anna Claire Christoffer
    build:
      context: .docker/site
      dockerfile: Dockerfile
    volumes:
      - ./:/opt
    ports: 
      - "1313:1313"
    command: hugo server -s /opt/annachristoffer -b https://annachristoffer.dev/ --appendPort=false --config=/opt/annachristoffer/config.dev.toml --bind "0.0.0.0"

  ac-nginx-development:
    container_name: nginx-dev
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.development.conf
        ssl_o: Dev
        ssl_cn: annachristoffer.dev
    volumes: 
      - ./media:/opt/media
    links: 
      - ac-site-development
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"

  ac-assets-development:
    image: node:7.7.4
    container_name: assetbuild-dev
    volumes: 
      - ./:/opt
    links:
      - ac-site-development
    depends_on:
      - ac-site-development
    command: bash -c "cd /opt && npm install -g gulp && npm install -g bower && npm link gulp && npm install && gulp"

volumes:
  data:
    driver: 'local'