version: '3'

services:

  ac-site:
    container_name: gohugo-staging
    environment: 
      - HUGO_TITLE=Anna Claire Christoffer
    build:
      context: .docker/site
      dockerfile: Dockerfile
    volumes:
      - ./:/opt
    command: hugo -s ./annachristoffer -b https://annachristoffer.staging --config=./annachristoffer/config.staging.toml -d ../public

  ac-nginx:
    container_name: nginx-staging
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args: 
        ssl_cn: annachristoffer.dev
    volumes: 
      - ./media:/opt/media
    links: 
      - ac-site
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"

  ac-assets:
    image: node:7.7.4
    container_name: assetbuild-staging
    volumes: 
      - ./:/opt
    links:
      - ac-site
    depends_on:
      - ac-site
    command: bash -c "cd /opt && npm install -g gulp && npm install -g bower && npm link gulp && npm install && gulp"

volumes:
  data:
    driver: 'local'