languageCode 		= "en-ie"
baseURL 			= "https://annachristoffer.staging/"
MetaDataFormat		= "yaml"
disableLiveReload	= true
watch				= true

[params]
	description 	= "Description for Anna Claire Christoffer"
	teaser			= "Hi. I am Anna and I am an Art Director based in Berlin, Germany."
	author 			= "Anna Claire Christoffer"
	pageBase		= "https://annachristoffer.staging/"
	mediaBase		= "https://media.annachristoffer.staging/"

[[menu.main]]
	name 		= "projects"
	identifier 	= "projects"
	url 		= "/"
	weight 		= 1
[[menu.main]]
	name 		= "about"
	identifier 	= "about"
	url 		= "/about"
	weight		= 2
[[menu.main]]
	name 		= "cv"
	identifier 	= "cv"
	url 		= "/cv"
	weight 		= 3
