languageCode 		= "en-ie"
baseURL 			= "http://annachristoffer.dev"
themesDir 			= "themes"
theme 				= "portfolio"
MetaDataFormat		= "yaml"
disableLiveReload	= true
watch				= true

[params]
	description = "Description for Anna Claire Christoffer"
	author = "Anna Claire Christoffer"