languageCode 		= "en-ie"
baseURL 			= "http://annachristoffer.dev/"
MetaDataFormat		= "yaml"
disableLiveReload	= true
watch				= true

[params]
	description 	= "Description for Anna Claire Christoffer"
	author 			= "Anna Claire Christoffer"
	pageBase		= "http://annachristoffer.dev/"
	mediaBase		= "http://media.annachristoffer.dev/"

[[menu.main]]
	name 		= "projects"
	identifier 	= "projects"
	url 		= "/"
	weight 		= 1
[[menu.main]]
	name 		= "about"
	identifier 	= "about"
	url 		= "/about"
	weight		= 2
[[menu.main]]
	name 		= "cv"
	identifier 	= "cv"
	url 		= "/cv"
	weight 		= 3
