languageCode 		= "en-ie"
baseURL 			= "http://annachristoffer.dev/"
MetaDataFormat		= "yaml"
disableLiveReload	= true
watch				= true

[params]
	description 	= "Description for Anna Claire Christoffer"
	author 			= "Anna Claire Christoffer"
	pageBase		= "http://annachristoffer.dev/"