---
languageCode:       "en-ie"
disableLiveReload:  true
watch:              true
title:              "Anna Claire Christoffer"

params:
  description:  "Description for Anna Claire Christoffer"
  teaser:       "Hi. I am Anna and I am an Art Director based in Berlin, Germany."
  author:       "Anna Claire Christoffer"
  mediaBase:    ""
  noindex:      true

menu:
  main:
    - name:       "Projects"
      identifier: "projects"
      url:        "/projects"
      weight:     1

    - name:       "About"
      identifier: "about"
      url:        "/about"
      weight:     2
...